config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :users, only: [:show]
  resources :posts
  resources :topics
  resources :categories

  root "categories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :category, required: false
  has_many :categories
  has_many :topics

  scope :root, -> { where category: nil }
  scope :by_date, -> { order created_at: :desc }
  scope :by_name, -> { order name: :asc }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  
  scope :by_date, -> { order created_at: :desc }

end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :posts

  scope :by_date, -> { order created_at: :desc }
end

app/models/user.rb
class User < ApplicationRecord
    enum role: [ :user, :admin ]
    has_many :posts
    has_many :topics
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])

  end

  def index
    @categories = Category.root.by_name
    @topics = Topic.limit(9).by_date
    @posts = Post.limit(9).by_date
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @topic = Topic.find(@post.topic_id)
  end

  def create
    @post = Post.create! post_params
    redirect_to @post.topic
  end

  private

  def post_params
    params.require(:post).permit(:body, :topic_id).merge user: current_user
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new(category_id: params[:category_id])
  end

  def create
    @topic = Topic.create! topic_params
    redirect_to @topic.category
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :body, :category_id).merge user: current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/categories/_category.html.erb
<div class="button">
    <%= link_to category.name, category, class: :button %>
</div>

app/views/categories/index.html.erb
<%= render "layouts/header" %>
<section id="page-categories">
  <h1>Categories</h1>
    <div class="categories">
      <%= render @categories %><br>
    </div>
</section>
<section id="page-topics">
  <h2>Latest Topics:</h2>
    <div class="topics">
      <%= render @topics %>
    </div>
</section>
<section id="page-posts">
  <h2 class="no-margin">Latest Posts:</h2>
    <div class="posts">
      <%= render @posts %>
    </div>
</section>

app/views/categories/show.html.erb
<%= render 'layouts/headerin' %>
<% if @category.categories.empty? %>
  <div class="categories padding-top">
    <div class="button">
      <%= link_to "Home", categories_path, class: :button %>
    </div>
  </div>
<% else %>
  <h1 class="size18">Categories</h1>
    <div class="categories">
      <div class="button">
        <%= link_to "Home", categories_path, class: :button %>
      </div>
      <%= render @category.categories %>
    </div>
<% end %>
<h1 class="size18 no-center">Topics</h1>
<% if @category.topics.empty? %>
  <%= link_to "+ new topic", new_topic_path(category_id: @category.id), class: :new_topic %>
  <p>No topics in this category</p>
<% else %>
  <%= link_to "+ new topic", new_topic_path(category_id: @category.id), class: :new_topic %>
  <%= render @category.topics %>
<% end %>

app/views/layouts/_header.html.erb
<header class="header">
  <section class="statusbar">
    <% if signed_in? %>
      <p>
      <%= current_user.email %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: :redlink %>
        <%if current_user.admin? %>
          <%=  link_to(image_tag("user-1.png", size: "32x32", alt: "Admin", class:"status-logo"), "/admin") %>
        <% else %>
          <%=  image_tag("user.png", size: "32x32", alt: "User", class: "status-logo") %>
        <% end %>
      <% else %>
      <%= link_to "Login", new_user_session_path, class: :greenlink %>
      </p>
    <% end %>
    <div class="justify-center">
      <p><%= link_to(image_tag("saitslogo.png", size: "300x150", alt: "SAITS", class: "saits-logo"), root_path, {class: "saits-logo"}) %></p>
    </div>
    <div class="justify-center">
      <h1 class="color-green">s</h1><h1 class="color-white">Forum</h1>
    </div>
    <div class="justify-center">
      <%= render 'layouts/navbar' %>
    </div>
  </header>
</section>

app/views/layouts/_headerin.html.erb
<header class="header-in-forum">
  <section class="statusbar">
    <% if signed_in? %>

      <p>
      <%= current_user.email %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: :redlink %>
        <%if current_user.admin? %>
          <%=  link_to(image_tag("user-1.png", size: "32x32", alt: "Admin", class:"status-logo"), "/admin") %>
        <% else %>
          <%=  image_tag("user.png", size: "32x32", alt: "User", class: "status-logo") %>
        <% end %>
      <% else %>
      <%= link_to "Login", new_user_session_path, class: :greenlink %>
      </p>
    <% end %>
    <div class="justify-center">
      <p><%= link_to(image_tag("saitslogo.png", size: "300x150", alt: "SAITS", class: "saits-logo-nomargin"), root_path, {class: "saits-logo"}) %></p>
    </div>
    <div class="justify-center">
      <h1 class="color-green">s</h1><h1 class="color-white">Forum</h1>
    </div>
  </header>
</section>

app/views/layouts/_navbar.html.erb
<nav class="nav-box">
        <ul class="menu">
          <li><a href="#page-categories">categories</a></li>
          <li><a href="#page-topics">latest topics</a></li>
          <li><a href="#page-posts">latest posts</a></li>
        </ul>
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sforum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%# postsform %>
<h2>Reply</h2>
<%= form_for(Post.new(topic: @topic), remote: false) do |form| %>
  <%= form.hidden_field :topic_id %>
  <%= form.text_area :body, cols:"70", rows: "5", class: :input_form %> <br>
  <%= form.submit 'Create Post', class: :submit_button %>
<% end %>

app/views/posts/_post.html.erb
<div class="posts-card">
<p class="no-margin">
  <%= link_to post.body, post %><br>
  <span class="text-small">Topic: <%= link_to post.topic.name, post.topic%><br>
  Author: <%= post.user.email %></span>
</p>
</div>

app/views/posts/_testpost.html.erb
<% @topic.posts.by_date.each do |post| %>

  <p><%= post.body %>
  - by <%= post.user.email %> <%= post.created_at.to_s(:short) %></p>

  <%end %>

app/views/posts/show.html.erb
<%= render 'layouts/headerin'%>
  <div class="categories">
    <div class="button padding-top ">
      <%= link_to "Home", categories_path, class: :button %>
    </div>
  </div>
<div class="justify-center">
  <div class="post-content">
      <h2 class="size3">
        <%= @topic.name %>
      </h2>
      <p class="size14">
        <%= @topic.body %>
      </p>
      <p class="size08">
        written by: <%= @topic.user.email %>
      </p>
      <%= render 'posts/form' %>
      <h2>Replies</h2>
    <%= render 'posts/testpost'  %>
  </div>
</div>

app/views/topics/_form.html.erb
<%# topic form %>
<h2> New topic </h2>
<%= form_for @topic do |form| %>
  <%= form.hidden_field :category_id %>
  <%= form.label :title%><br>
  <%= form.text_field :name, class: :input_form %><br>
  <%= form.label :message %> <br>
  <%= form.text_area :body, cols:"50", rows: "20", class: :input_form %><br>
  <%= form.submit 'Create Topic', class: :submit_button  %>
<% end %>

app/views/topics/_topic.html.erb
<div class="topics-card">
<p class="no-margin no-deco">
  <%= link_to topic.name, topic %>
  <br><%= topic.posts.count %> Posts
  <br><%= topic.user.email %>
</p>
</div>

app/views/topics/new.html.erb
<%= render 'layouts/header'%>
<%= render 'form' %>

app/views/topics/show.html.erb
<%= render 'layouts/headerin'%>
  <div class="categories">
    <div class="button padding-top ">
      <%= link_to "Home", categories_path, class: :button %>
    </div>
  </div>
<div class="justify-center">
  <div class="post-content">
      <h2 class="size3">
        <%= @topic.name %>
      </h2>
      <p class="size14">
        <%= @topic.body %>
      </p>
      <p class="size08">
        written by: <%= @topic.user.email %>
      </p>
      <%= render 'posts/form' %>
      <h2>Replies</h2>
    <%= render 'posts/testpost'  %>
  </div>
</div>